### PR TITLE
Insulin tracking

### PR DESCRIPTION
**Pull request by nosarcasm**

### CODE REVIEW

**Comment by nosarcasm** [comment]
Needs to be fixed first before prettifying step

**Comment by daniel-ranti** [comment]
I thought you merged this branch...I got an email saying that you had merged it a few weeks ago which is why I opened a new PR haha. the prettifying steps fix sloppy things I did in this branch too

**Comment by nosarcasm** [comment]
Yeah I reverted the merge and then made a new PR

**Comment by daniel-ranti** [comment]
I am going to merge this branch. The prettifying branch was created to fix the errors in this branch under the assumption that it already been merged.

**Pull request merged**
